

class mlg {
       public static void main(String args[]) {
	   Scanner answer = new Scanner(System.in);
	   String userInput;
	   System.out.print.ln("Are you the best? (Yes/No)");
	   userInput = answer.next();
               if(userInput.equals = ("Yes")){	   
				       System.out.println("I don't care");
			   } else if(user Input.equals = ("No")){
                       System.out.println("None of us are");
			   } else {	
                       System.out.println("No surprise")
			   }
	   }
}	   
